### PR TITLE
Faker.NET Mono integration

### PR DESCRIPTION
**Pull request by ilich**
Hi Jon,

Thank you for the great tool. It is quite helpful for unit-testing. I have done few changes. I hope you will find them useful:
1. Removed sugar.dll dependency to simplify the project. I moved few methods to Faker.NET code.
2. Added MonoDevelop projects.
3. Added NAnt build to be able to build on Windows and on Linux without IDE.
4. Converted unit-tests from Ruby to C#.
5. Small refactoring.

Please let me know if you have any question or concern. 

Best regards,

Ilya

### CODE REVIEW

**Comment by jonwingfield** [comment]
Thanks for your work on this.  I hope to finish reviewing your changes tomorrow at some point.

A few questions:
- I presume that you migrated to all C# because of mono support?  I lacked that foresight when originally building this project.
- I'm a little concerned about the method name changes, only because they are breaking changes and anyone using the library could have some significant refactoring to do as a result.

**Comment by ilich** [comment]
> I presume that you migrated to all C# because of mono support? 

Mono support is one point. Another point is not all C# developers are familiar with Ruby but all of them are able to read C# code. Unit-tests are the best documentation you can have. That's why I converted tests to C#.

> I'm a little concerned about the method name changes...

That's a good point. I didn't think about it. Please don't merge my changes to master. I will add the removed methods back, change them to use new methods and mark them as obsolete. Then we are safe of breaking anybody code. I will upgrade my pull request when it's done.

**Comment by ilich** [comment]
I have returned legacy methods and marked them as obsolete. You can merge the changes now. I would also recommend to run legacy unit-tests if you have them to be sure that legacy methods work as expected.

Please let me know if you have other concerns.

**Comment by jonwingfield** [comment]
Ok, great.  I'll review and run the tests shortly...  Thanks for your help!

**Pull request merged**
